# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')),
            ],
            options={
                'verbose_name_plural': '买方',
                'verbose_name': '买方',
            },
        ),
        migrations.CreateModel(
            name='CourseClassFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('it', 'IT互联网'), ('language', '语言留学'), ('design', '创意设计'), ('life', '兴趣生活'), ('plant', '生产种植'), ('edu', '升学考研'), ('certificate', '公培考证')], max_length=15, verbose_name='第一分类')),
            ],
            options={
                'verbose_name_plural': '第一分类',
                'verbose_name': '第一分类',
            },
        ),
        migrations.CreateModel(
            name='CourseClassSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='第二分类')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClassFirst', verbose_name='第一分类')),
            ],
            options={
                'verbose_name_plural': '第二分类',
                'verbose_name': '第二分类',
            },
        ),
        migrations.CreateModel(
            name='CourseClassThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='课程名称')),
                ('price', models.CharField(max_length=6, verbose_name='课程价格')),
                ('learn_time', models.CharField(max_length=10, verbose_name='课程时长')),
                ('nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='课程封面')),
                ('describe', models.ImageField(upload_to='', verbose_name='课程简介')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击人数')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClassSecond', verbose_name='第二分类')),
            ],
            options={
                'verbose_name_plural': '课程',
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='课程名')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='课程时间')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClassThird', verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '章节 ',
                'verbose_name': '章节 ',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20, verbose_name='老师名字')),
                ('teacher_des', models.CharField(max_length=100, verbose_name='老师描述')),
                ('teacher_image', models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像')),
                ('teacher_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClassThird', verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '老师',
                'verbose_name': '老师',
            },
        ),
        migrations.AddField(
            model_name='buy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClassThird', verbose_name='课程'),
        ),
    ]
