# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180508_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclassthird',
            name='learn_time',
            field=models.IntegerField(verbose_name='课程时长'),
        ),
    ]
