# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180508_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclassthird',
            name='learn_time',
            field=models.CharField(max_length=10, verbose_name='课程时长'),
        ),
        migrations.AlterField(
            model_name='courseclassthird',
            name='price',
            field=models.IntegerField(verbose_name='课程价格'),
        ),
    ]
