# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180508_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='courseclassthird',
            options={'verbose_name': '第三类学科', 'verbose_name_plural': '第三类学科'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='sort',
            new_name='sort4',
        ),
        migrations.RenameField(
            model_name='courseclasssecond',
            old_name='sort',
            new_name='sort2',
        ),
        migrations.RenameField(
            model_name='courseclassthird',
            old_name='sort',
            new_name='sort3',
        ),
    ]
