# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180509_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程名'),
        ),
    ]
