# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180509_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程名'),
        ),
    ]
