"""
Django settings for tanzhou project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9rvnog6rl-v%n#$@pkm5r6fv56$i(o@&qp6n^n^4t6(dfj@m8a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'information.apps.InformationConfig',
    'course',
    'captcha',
    'pure_pagination',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tanzhou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'tanzhou.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tanzhoudb',
        'USER': 'wangjun',
        'PASSWORD': 'qwe123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'information.UserInfor'
AUTHENTICATION_BACKENDS = ('information.views.MyBackend',)

LOGIN_URL = '/user/login/'

# EMAIL_HOST = 'smtp.qq.com'
# EMAIL_PORT = 465  # SSL#第三种配置
# # EMAIL_PORT=587#TSL#第二种配置
# # EMAIL_PORT=25#第一种配置
# EMAIL_HOST_USER = '1019122831@qq.com'
# EMAIL_HOST_PASSWORD = 'fvekojzdtztvbbhb'
# EMAIL_USER_SSL = True  # 第三种配置
# # EMAIL_USER_TSL=True#第一，二种配置
# EMAIL_FROM = '1019122831@qq.com'



# 邮件引擎
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# smtp邮箱的host地址，每个邮箱都是不同的
EMAIL_HOST = 'smtp.163.com'
# smtp邮箱的端口
EMAIL_PORT = 25
# 发送邮件的邮箱（发件人）
EMAIL_HOST_USER = '15705107305@163.com'
# 在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = '19930510wj'
# 收件人看到的发件人
EMAIL_FROM = 'store <15705107305@163.com>'  # 需要和邮箱号码一致

PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 10,  # 这个是显示中间有多少个按键
    'MARGIN_PAGES_DISPLAYED': 2,  # 是将显示的第一页和最后一页相邻的页数（默认值为2）

    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}
