# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20180428_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
