# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20180506_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='qq',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='QQ'),
        ),
    ]
